import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="zh">
      <head>
        <link href="/svg/canlendar.svg" rel="icon" type="image/x-icon"></link>
      </head>
      {/*  className={inter.className} */}
      <body>{children}</body>
    </html>
  )
}
